name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
- name: Build the hello-docker Docker image
run: |
       docker build . --file Dockerfile --tag NewDock:$(date +%s)
       echo "Hello World!"
       uname -ar