name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd /home/runner/work/v64/v64/websockproxy/ && docker build . --file Dockerfile --tag my-image-name

  runing:

     runs-on: ubuntu-latest 

     steps:
     - uses: actions/checkout@v3
     - name: Running the app now
       run: docker run -p 8080:80 benjamincburns/jor1k-relay:latest -d --name my-image-name
