name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag v86-networking:$(date +%s) && docker rm relay && docker run --privileged -p 8080:80 --name relay benjamincburns/jor1k-relay
